spring:
  threads:
    virtual:
      enabled: true
  application:
    name: market-data-service

influx:
  url: http://localhost:8086
  token: my-super-secret-token
  org: my-org
  bucket: crypto-bucket

market:
  real-symbols:
    - BTCUSDT
    - ETHUSDT
  simulated-count: 5

